## Part-1: Keşifçi Veri Analizi ve Veri Görselleştirme

In [2]:
import pandas as pd

# Veri setini yükleme
df = pd.read_csv('StudentPerformanceFactors.csv')

### Veri Seti Hikayesi

Bu veri seti, sınavlardaki öğrenci performansını etkileyen çeşitli faktörlerin kapsamlı bir özetini sunmaktadır. Ders çalışma alışkanlıkları, devam durumu, ebeveyn katılımı ve akademik başarıyı etkileyen diğer etmenlerle ilgili bilgileri içermektedir.

### Veri Seti Özellikler

- **Hours_Studied**: Haftada ders çalışmaya harcanan saat sayısı.
- **Attendance**: Derslere katılım yüzdesi.
- **Parental_Involvement**: Öğrencinin eğitimine ebeveyn katılım seviyesi (Düşük, Orta, Yüksek).
- **Access_to_Resources**: Eğitim kaynaklarına erişim durumu (Düşük, Orta, Yüksek).
- **Extracurricular_Activities**: Ders dışı etkinliklere katılım (Evet, Hayır).
- **Sleep_Hours**: Her gece ortalama uyku saati.
- **Previous_Scores**: Önceki sınavlardan alınan puanlar.
- **Motivation_Level**: Öğrencinin motivasyon seviyesi (Düşük, Orta, Yüksek).
- **Internet_Access**: İnternet erişimi durumu (Evet, Hayır).
- **Tutoring_Sessions**: Aylık alınan özel ders sayısı.
- **Family_Income**: Aile gelir seviyesi (Düşük, Orta, Yüksek).
- **Teacher_Quality**: Öğretmenlerin kalitesi (Düşük, Orta, Yüksek).
- **School_Type**: Katılınan okul türü (Devlet, Özel).
- **Peer_Influence**: Arkadaşların akademik performansa etkisi (Pozitif, Nötr, Negatif).
- **Physical_Activity**: Haftada yapılan ortalama fiziksel aktivite saati.
- **Learning_Disabilities**: Öğrenme güçlüğü olup olmadığı (Evet, Hayır).
- **Parental_Education_Level**: Ebeveynlerin en yüksek eğitim seviyesi (Lise, Üniversite, Lisansüstü).
- **Distance_from_Home**: Evden okula olan mesafe (Yakın, Orta, Uzak).
- **Gender**: Öğrencinin cinsiyeti (Erkrek, Kadın).
- **Exam_Scoe**: Final sınavı puanı.

In [4]:
# Satır ve sütun sayısını öğrenmek için
print("Satır sayısı (Gözlem Sayısı) :", df.shape[0])
print("Sütun sayısı (Değişken Sayısı) :", df.shape[1])

Satır sayısı (Gözlem Sayısı) : 6607
Sütun sayısı (Değişken Sayısı) : 20

In [5]:
# Genel bilgi için
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB
None

In [6]:
# Betimsel istatistikler
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [7]:
# Kategorik değişkenlerin her bir sınıfının frekansı
for col in df.select_dtypes(include=['object']).columns:
    print(f"{col} sınıf sayıları ve frekansları:")
    print(df[col].value_counts())
    print("\n")

Parental_Involvement sınıf sayıları ve frekansları:
Parental_Involvement
Medium    3362
High      1908
Low       1337
Name: count, dtype: int64


Access_to_Resources sınıf sayıları ve frekansları:
Access_to_Resources
Medium    3319
High      1975
Low       1313
Name: count, dtype: int64


Extracurricular_Activities sınıf sayıları ve frekansları:
Extracurricular_Activities
Yes    3938
No     2669
Name: count, dtype: int64


Motivation_Level sınıf sayıları ve frekansları:
Motivation_Level
Medium    3351
Low       1937
High      1319
Name: count, dtype: int64


Internet_Access sınıf sayıları ve frekansları:
Internet_Access
Yes    6108
No      499
Name: count, dtype: int64


Family_Income sınıf sayıları ve frekansları:
Family_Income
Low       2672
Medium    2666
High      1269
Name: count, dtype: int64


Teacher_Quality sınıf sayıları ve frekansları:
Teacher_Quality
Medium    3925
High      1947
Low        657
Name: count, dtype: int64


School_Type sınıf sayıları ve frekansları:
School_Type
Public     4598
Private    2009
Name: count, dtype: int64


Peer_Influence sınıf sayıları ve frekansları:
Peer_Influence
Positive    2638
Neutral     2592
Negative    1377
Name: count, dtype: int64


Learning_Disabilities sınıf sayıları ve frekansları:
Learning_Disabilities
No     5912
Yes     695
Name: count, dtype: int64


Parental_Education_Level sınıf sayıları ve frekansları:
Parental_Education_Level
High School     3223
College         1989
Postgraduate    1305
Name: count, dtype: int64


Distance_from_Home sınıf sayıları ve frekansları:
Distance_from_Home
Near        3884
Moderate    1998
Far          658
Name: count, dtype: int64


Gender sınıf sayıları ve frekansları:
Gender
Male      3814
Female    2793
Name: count, dtype: int64

In [8]:
# Eksik veri sayısı
print("Eksik veri sayıları:")
print(df.isnull().sum())

Eksik veri sayıları:
Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64